### ISSUE TITLE
Unable to create invoice

### ISSUE THREAD

**Issue by monukanyal** [XeroAPI/xero-node#107]
Hello,

I am not able to create invoice. I am getting response like below:
{ Error: PUT call failed with: 400
    at /Users/macmini/Documents/myds-node/node_modules/xero-node/lib/application.js:145:42
    at passBackControl (/Users/macmini/Documents/myds-node/node_modules/xero-node/lib/oauth/oauth.js:406:25)
    at IncomingMessage.<anonymous> (/Users/macmini/Documents/myds-node/node_modules/xero-node/lib/oauth/oauth.js:422:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  data: 
   { ErrorNumber: 10,
     Type: 'ValidationException',
     Message: 'A validation exception occurred',
     Elements: [ [Object] ] } }

Please provide solution.

**Comment by monukanyal** [comment]
when i am not putting 'Status' , it is creating invoice as a draft. but why it is not creating invoice when putting 'Status' to 'SUBMITTED'.  In this case , i am getting 400 error with validation exception.
please let me know , am i missing anything?

**Comment by jordanwalsh23** [comment]
Submitted is not a valid status.

Try AUTHORISED instead if you want to create an approved invoice.

You can also catch the error and do further inspection of your error object
in the handler.

**Comment by monukanyal** [comment]
submitted is working now, problem was in accountcode , i was passing accountid.

**Comment by monukanyal** [comment]
Please i need you help.
I am hitting xero api conditionally. but response from xero is coming late as expected so beacause of this my variable is updating its value .please can you provide me any solution, i will be thankful to you.
