### ISSUE TITLE
Issue on AWS Lambda, but works locally 

### ISSUE THREAD

**Issue by lexakozakov** [XeroAPI/xero-node#122]
Hello,

I tried to fetch a contact (XeroClient.core.contacts.getContact(ContactId) ) and it worked locally. I uploaded this code to AWS Lambda and I got the error below:

`
2017-10-19T19:35:05.722Z	9ac66835-b504-11e7-a7a9-bb98e4bdb519	SyntaxError: Unexpected token ...
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/node_modules/xero-node/lib/entity_helpers/accounting/organisations.js:3:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at /var/task/node_modules/xero-node/lib/core.js:43:27
at /var/task/node_modules/xero-node/node_modules/lodash/lodash.js:4944:15
at baseForOwn (/var/task/node_modules/xero-node/node_modules/lodash/lodash.js:3001:24)
at /var/task/node_modules/xero-node/node_modules/lodash/lodash.js:4913:18
at Function.forEach (/var/task/node_modules/xero-node/node_modules/lodash/lodash.js:9359:14)
at new Core (/var/task/node_modules/xero-node/lib/core.js:42:5)
at Application (/var/task/node_modules/xero-node/lib/application.js:43:16)
at new Application.extend.constructor (/var/task/node_modules/xero-node/lib/application.js:562:21)
at module.exports.handler.client.core.contacts.getContact.then.data.catch (/var/task/lambda/notifications/request_test.js:18:15)
`

**Comment by philals** [comment]
Hi @lexakozakov. I see you closed the issue. Do you mind posting the solution for others? Cheers

**Comment by lexakozakov** [comment]
Oh! Don't forget to check what node version is set in Lambda. It was 4.3 and I changed to 6.10.
