### ISSUE TITLE
PUT call failed: undefined status code and empty exception

### ISSUE THREAD

**Issue by chris-schertenlieb** [XeroAPI/xero-node#149]
I am using a firebase cloud function to execute some invoice creation via this api. When my function runs I get the following fatal error: 
`Error: PUT call failed with: undefined and exception: ""`
where `undefined` is the error status code and `""` is the exception string. 

What I'm attempting to do is upon some event in firebase, create an invoice in xero. After requiring the xero-node package, my logic flows as follows: 

**1.** grab my configuration values i have stored in firebase:
`config = { consumerKey: 'foo', consumerSecret: 'bar', userAgent: 'cloud' }`
**2.** initialize my xero client:
`const xeroClient = new xero.PrivateApplication(config);`
**3.** Grab my event data (not shown) and make an invoice out of it
`var invoice = {
    Type: 'ACCREC',
    Contact: {
        ContactID: '1234567890'
    },
    Status: 'DRAFT',
    LineItems: [ stuff ]
};`
**4.** Make my xero invoice object 
`xeroInvoice = xeroClient.core.invoices.newInvoice(invoice);`
**5.** Make the PUT call
`xeroInvoice.save().then(...`

With so little response information I'm not sure what's going wrong. I can't seem to find any reports of people getting an empty error back, and there's nothing about it in the [response code documentation](https://developer.xero.com/documentation/api/http-response-codes).

The entire error log: 
`Error: PUT call failed with: undefined and exception: ""
    at /user_code/node_modules/xero-node/lib/application.js:159:42
    at Writable.<anonymous> (/user_code/node_modules/xero-node/lib/oauth/oauth.js:432:13)
    at emitOne (events.js:96:13)
    at Writable.emit (events.js:188:7)
    at ClientRequest.eventHandlers.(anonymous function) (/user_code/node_modules/xero-node/node_modules/follow-redirects/index.js:22:22)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)`

I'd be happy to clarify anything upon request. Thanks in advance.

**Comment by philals** [comment]
Hi @chris-schertenlieb Thanks for the issue. 

Are you able to see any logs in https://app.xero.com/Application/history ?

**Comment by SidneyAllen** [comment]
Hi @chris-schertenlieb 

You don't mention the privateKey path in your config.  Just confirming you're getting the privateKey string set somewhere in your application.  

Thanks

**Comment by philals** [comment]
Hi @chris-schertenlieb 

We're doing a bit of work around error codes and exceptions. Can you give this branch a go and see if it helps? https://github.com/XeroAPI/xero-node/pull/169

Or try taking the latest version - there have been some changes since your initial post.

Thanks

**Comment by philals** [comment]
Closing due to inactivity. Feel free to reopen. Thanks.
