### ISSUE TITLE
v3 - savePDF ('ERR_INVALID_ARG_TYPE', 'listener', 'Function')

### ISSUE THREAD

**Issue by DaveCLowe** [XeroAPI/xero-node#191]
"xero-node": "^3.0.0-alpha.6"

```
try {
    savePathPDF = path.join(__dirname, myInvoice.InvoiceNumber + '.pdf');
    log.info('Saving PDF to: ' + savePathPDF);
    const response = await xero.invoices.savePDF({
      InvoiceID: myInvoice.InvoiceID,
      savePath: savePathPDF,
    });
  } catch (err) {
    log.error(err);
  }
```

PDF is saved successfully, but error thrown:

[0] events.js:180
[0]     throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'listener', 'Function');
[0]     ^
[0]
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
[0]     at _addListener (events.js:180:11)
[0]     at WriteStream.addListener (events.js:240:10)
[0]     at WriteStream.close (fs.js:2298:10)
[0]     at IncomingMessage.<anonymous> (xxxx/node_modules/xero-node/lib/internals/OAuth1HttpClient.js:150:37)
[0]     at IncomingMessage.emit (events.js:164:20)
[0]     at endReadableNT (_stream_readable.js:1062:12)
[0]     at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by philals** [comment]
Thanks for the issue. Will check it out next time I'm in the office.

**Comment by philals** [comment]
Hi

So this is working for me. And the test for this function is green in CI.

What version of node are you using?

**Comment by philals** [comment]
I'm using 8.9.1

**Comment by philals** [comment]
@DaveCLowe I have also pushed a new version which removes one line of code which was not needed. I don't think this will fix the issue though.

Are you able to run this test: https://github.com/XeroAPI/xero-node/blob/v3/src/__integration_tests__/invoices.integration.tests.ts#L61

Here is some details on running the tests: https://github.com/XeroAPI/xero-node/tree/v3#running-the-tests

**Comment by philals** [comment]
So my latest push adds an extra eventListner.

Before it was only listing to `end` it's now also listening to `close`. 

In my tests only `end` gets triggered. But maybe with your Invoice `close` gets triggered.

Are you able to give the latest a spin?

**Comment by DaveCLowe** [comment]
Hey @philals - whatever the problem was, it wasn't related to this module. The tests all passed fine. My code is also working fine now too thanks. Will close this.
