### ISSUE TITLE
Error on creating Receipt 

### ISSUE THREAD

**Issue by Dav1DH** [XeroAPI/xero-node#201]
I have problem on creating a receipt with Xero-node module. My code looks like this.

```
exports.createReceipt = () => {
  return new Promise((resolve, reject) => {
    xero.receipts.create({
      Date: new Date(),
      User: {
        UserID: 'cf354e7a-bc04-4ad5-8960-74114638fb63'
      },
      Contact: {
        ContactID: '4a6f573a-a87b-49d5-9d9c-71c9bc5c8419'
      },
      LineAmountTypes: 'Inclusive',
      LineItems: [
        {
          Description: 'Coffee with client to discuss support contract',
          UnitAmount: '13.80',
          AccountCode: '420'
        }
      ],
      Total: '13.80'
    }).then((data) => {
      resolve(data)
    }).catch((err) => {
      reject(err)
    })
  })
}
```
And after when I try to get the promise I am getting this in console from promise reject.

```
{ Error: XeroError: statusCode=400 data={
  "ErrorNumber": 14,
  "Type": "PostDataInvalidException",
  "Message": "JSON for post data was invalid,Error reading string. Unexpected token: StartObject. Path 'User', line 1, position 43."
}
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  statusCode: 400,
  data: '{\r\n  "ErrorNumber": 14,\r\n  "Type": "PostDataInvalidException",\r\n  "Message": "JSON for post data was invalid,Error reading string. Unexpected token: StartObject. Path \'User\', line 1, position 43."\r\n}',
  headers: 
   { 'cache-control': 'private',
     'content-type': 'application/json; charset=utf-8',
     date: 'Wed, 16 May 2018 10:42:17 GMT',
     'strict-transport-security': 'max-age=31536000',
     'www-authenticate': 'OAuth Realm="api.xero.com"',
     'xero-cell': 'egeby',
     'content-length': '199',
     connection: 'Close' } }
```
It seems having some problems with parsing the JSON.

**Comment by philals** [comment]
Thanks for the issue. @admo26 will get back to you shortly.

**Comment by nickngsr** [comment]
The way I had to get round this was to encompass the receipt object like so:
```javascript
const reciept = xero.receipts.create({Receipts: [{...}]})
```

**Comment by Dav1DH** [comment]
That is right and working ok. But in this case we are sending an array. The problem is solved but please check the TS interfaces and check the create part in TS. you can see that there is 2 ways to do this.
1) with object
2) with array. 

I am just wondering why the 1 way is not working and another thing is it possible to put some comments in TS interfaces. If you will allow me I will be happy to contribute and help you with this.

**Comment by nickngsr** [comment]
It would appear here that the single receipt post is not working / does not actually exist and all requests must be in the 'Receipts' container

**Comment by philals** [comment]
Thanks for the discussion. 

Looks like we have a way around it.
