### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by schinns** [XeroAPI/xero-node#242]
I am sorry, I am not sure how to duplicate the error. Every now and this error is thrown and I am not sure how to trace down the cause. I have noticed it is usually happening when the server starts or restarts and makes a connection with xero. 

The only suspicion I have is that maybe this happens because the server has two different `XeroClient` connecting to two different providers.  If anyone has any clues please share!! Thank you!

I am using node-xero 3.0.7 and here is the error:

```
undefined:60227
      "FullyPaidOnD


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/ben/code/sms/node_modules/xero-node/lib/internals/OAuth1HttpClient.js:283:53
    at passBackControl (/Users/ben/code/sms/node_modules/oauth/lib/oauth.js:390:11)
    at IncomingMessage.<anonymous> (/Users/ben/code/sms/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by philals** [comment]
Hi Closing due to lack of response. Feel free to raise again with an example.

All the best
