### ISSUE TITLE
Socket Hang Up Error in AWS Lambda

### ISSUE THREAD

**Issue by clethrill** [XeroAPI/xero-node#268]
I have xero.js which is shared between a few different lambda functions. The whole oauth process works fine. However when I try to call getOrganisation() from a different lambda function later on, it fails seemingly every second invocation.

index.js

```
const Xero = require("./utilities/xero");
    const Authentication = require("./utilities/authentication");

    exports.handler = async (event) => {
        
        try {
            console.log(event);
            const cognitoUserId = await Authentication.getUserId(event.headers.AccessToken);
        
            const xero = new Xero(await Xero2.getAccessTokenFromDatabase(cognitoUserId));
    
            let response = await xero.getOrganisation();
            console.log(response);

            return response;
        } catch (error) {
            console.log(error);
            return;
        }

    };
```

xero.js
```
    const XeroClient = require('xero-node').AccountingAPIClient;

    const XeroConfig = {
	appType: "partner",
	consumerKey: process.env.xero_key,
	consumerSecret: process.env.xero_secret,
	callbackUrl: process.env.xero_callback,
        privateKeyPath: process.env.xero_private_key_path
    }

    class Xero {

        constructor(accessToken) {
            this._Xero = new XeroClient(XeroConfig, accessToken);
        }

        async getOrganisation() {
            return (await this._Xero.organisations.get()).Organisations[0];
        }

        async getRequestUrl() {
            const requestToken = await this._Xero.oauth1Client.getRequestToken();
            return xero.oauth1Client.buildAuthoriseUrl(requestToken);
        }

        async getAccessTokenFromRequest(oauth_verifier, requestTokens) {
            const accessToken = await this._Xero.oauth1Client.swapRequestTokenforAccessToken(requestTokens, oauth_verifier);
            return accessToken;
        }
    }

    module.exports = Xero;
```

So the first time I run the lambda function with index.js above it works and every logs fine and it returns the organisation. The second attempt before it even logs the `console.log(event);` line throws an error:

`Error: socket hang up
at createHangUpError (_http_client.js:299:15)
at TLSSocket.socketOnEnd (_http_client.js:391:23)
at emitNone (events.js:111:20)
at TLSSocket.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

**Comment by clethrill** [comment]
I seemed to have fixed this by re-running `npm install` and redeploying my Lambda function.
