### ISSUE TITLE
[v4] Cannot read property 'callback' of undefined

### ISSUE THREAD

**Issue by ezetaraborelli** [XeroAPI/xero-node#298]
**SDK you're using (please complete the following information):**
 - Version 4.0.2

**Describe the bug**
I'm playing a bit with the js example from the oAuth2 branch and when I try to create a contact inside the /organisation endpoint, I get an error from the library saying "Cannot read property 'callback' of undefined"

**To Reproduce**
1. In the JS example, add 'accounting.contacts' to the scopes, and this to the /organisation endpoint:
`const contact = await xero.accountingApi.createContact(xero.tenantIds[0], {Name: 'John'})`
2. Start the app
3. Follow the sign on flow

**Expected behavior**
It should create the contact

**Additional context**
I tried another endpoint in the same place (getting a single contact) and it worked fine, so I think the auth data is fine
[This](https://github.com/XeroAPI/xero-node/blob/e2ef8bf640e103ddd6dc8878015537c9f9bee882/src/xeroClient.ts#L54) is the line where it fails
This is the full error stack:

```
(node:10456) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'callback' of undefined
    at XeroClient.setAccessTokenFromRedirectUri (/Projects/testXero/node_modules/xero-node/dist/XeroClient.js:34:49)
    at /Projects/testXero/index.js:48:14
    at Layer.handle [as handle_request] (/Projects/testXero/node_modules/express/lib/router/layer.js:95:5)
    at next (/Projects/testXero/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Projects/testXero/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Projects/testXero/node_modules/express/lib/router/layer.js:95:5)
    at /Projects/testXero/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Projects/testXero/node_modules/express/lib/router/index.js:335:12)
    at next (/Projects/testXero/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/Projects/testXero/node_modules/express-session/index.js:495:7)
(node:10456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dillonparfitt** [comment]
Hi @ezetaraborelli 
I experienced the same issue when attempting to refresh a token, it is an annoying bug on their side. I resolved it by adding:
`await xero.buildConsentUrl();`
prior to the API call I was making.

**Comment by ezetaraborelli** [comment]
Hi @dillonparfitt it worked!! Thank!
Now I've found another issue, but I'll close this ticket and create another one.
