### ISSUE TITLE
Throwing error while requiring the module with version 4.0.5

### ISSUE THREAD

**Issue by sreejithsree11** [XeroAPI/xero-node#312]
internal/util.js:257
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
    at promisify (internal/util.js:257:11)
    at Object.<anonymous> (/home/sreejith/projects/testFolder/node_modules/jose/lib/jwk/key/rsa.js:13:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/sreejith/projects/testFolder/node_modules/jose/lib/jwk/import.js:9:16)

**Comment by SerKnight** [comment]
Hi @sreejithsree11 - please utilize the issue template for bug reports.. Closing this but feel free to re-open with all required fields:

https://github.com/XeroAPI/xero-node/issues/new?assignees=&labels=bug+reported+%28%3F%29&template=bug_report.md

We have a sample node app setup to show basic configuration:
> https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L705

There was just a recent NPM version upgrade to `4.0.6`
