### ISSUE TITLE
Throwing error while requiring the module with version 4.0.5 and 4.0.6

### ISSUE THREAD

**Issue by sreejithsree11** [XeroAPI/xero-node#314]
- Version - xero-node 4.0.6

- Throwing error while requiring the module with version 4.0.6

- Steps to reproduce the behavior:

1. NPM install the xero-node module
2. Require it in a js file (index.js)
3. Run it using node (node index.js)
4. I'm getting an error like
```

internal/util.js:257
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
    at promisify (internal/util.js:257:11)
    at Object.<anonymous> (/home/sreejith/projects/testFolder/node_modules/jose/lib/jwk/key/rsa.js:13:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/sreejith/projects/testFolder/node_modules/jose/lib/jwk/import.js:9:16)


```
**Expected behavior**
It should not throw any error on requiring the module

I tried with version 4.0.5 and 4.0.6 and still getting the same error.

**Comment by SidneyAllen** [comment]
Hi @sreejithsree11 

Can you check the version of node you are running?
`node -v`

Pretty sure I ran into this issue with the open-id and jose dependencies needing a higher version.

I believe the supported node runtime (in package.json engines as well readme) is ^10.13.0 || >=12.0.0 so again - your runtime didn't have the required crypto.generateKeyPair function

**Comment by SerKnight** [comment]
Hey @sreejithsree11 - yeah think Sid's on it its likely your package.lock keeping an older version of the jose/jwk lib? I just set up a barebones Node/Express/Xero-Node app to show you how the xero pkg should work on a fresh install.. 

```bash
node -v
v12.13.1
```

Please reference: https://github.com/SerKnight/xero-node-basic-app

If you still having troubles please re-open with  as much of your project's dependencies as you can. Its hard for us to tell what your other dependencies are that are causing this error.

**Comment by sreejithsree11** [comment]
Thanks @SidneyAllen, I'm updated the Node version and its working fine. Once again thank you.

Thanks @SerKnight for your support.
