### ISSUE TITLE
Xero-Node client is not supporting for node version 8.11.4

### ISSUE THREAD

**Issue by Vishanth** [XeroAPI/xero-node#383]
**Describe the bug**
Xero-Node client is not supporting for node version 8.11.4.

**To Reproduce**
Steps to reproduce the behaviour:
1. Running the app with node version 8.11.4

**Expected behaviour**
Expected to start the node server

**Error Log**
`/var/app/current/node_modules/jose/lib/help/rsa_primes.js:8
const ZERO = BigInt(0)
             ^
ReferenceError: BigInt is not defined
    at Object.<anonymous> (/var/app/current/node_modules/jose/lib/help/rsa_primes.js:8:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/node_modules/jose/lib/help/key_utils.js:11:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/node_modules/jose/lib/jwk/key/base.js:7:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/node_modules/jose/lib/help/get_key.js:2:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)`

**Additional context**
Xero-Node dependency -> [openid client](https://www.npmjs.com/package/openid-client) dependency -> jose (https://www.npmjs.com/package/jose)

**Jose package is only built for >=10.13.0 Node.js environment. Which makes Xero-Node supported for node version 10.13.0 and above.**

I would like to confirm if this is expected or any workaround for node version 8.11.4?

**Comment by SerKnight** [comment]
Hi Vishnath - thank you for reporting. Unfortunately you are correct in that this library is only supporting node versions 10+ We apologize for the inconvenience. Node vsn 8 has actually hit its deprecation point as of January 2020:

![](https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true)



> https://nodejs.org/en/about/releases/

**Comment by simonaberry** [comment]
We are getting the same error on node 10.2.1. 

We managed to use a BigInt polyfill, but then ran into promisify errors. 

Any workarounds ?
