### ISSUE TITLE
Multi item push fails

### ISSUE THREAD

**Issue by borisno2** [XeroAPI/xero-node#39]
Multi item push fails with the following error:
```
Mongoose model 'error' event fired on 'Invoice' with error:
 entity.toXml is not a function TypeError: entity.toXml is not a function
    at /Users/joshuacalder/Development/xero-ucrm-sync/node_modules/xero-node/lib/entity_helpers/entity_helper.js:29:27
    at arrayMap (/Users/joshuacalder/Development/xero-ucrm-sync/node_modules/lodash/lodash.js:660:23)
    at Function.map (/Users/joshuacalder/Development/xero-ucrm-sync/node_modules/lodash/lodash.js:9571:14)
    at constructor.saveEntities (/Users/joshuacalder/Development/xero-ucrm-sync/node_modules/xero-node/lib/entity_helpers/entity_helper.js:28:29)
    at constructor.saveInvoices (/Users/joshuacalder/Development/xero-ucrm-sync/node_modules/xero-node/lib/entity_helpers/accounting/invoices.js:30:21)
```

**Comment by jordanwalsh23** [comment]
PR #41 has been added to resolve this issue.

Please try again and close the issue if resolved.

**Comment by jordanwalsh23** [comment]
xero-node@2.1.7

**Comment by borisno2** [comment]
@jordanwalsh23 I am still getting a `TypeError: entity.toXml is not a function` on both `saveInvoices` and `saveItems`

**Comment by jordanwalsh23** [comment]
Can you post your code?

The tests are passing so I'm confident the functions are working.

**Comment by borisno2** [comment]
Never mind it looks to be working once I fixed up a few things, doesn't look like it likes pushing one item using using `saveItems` or `saveInvoices`
Thanks for fixing this up!
