### ISSUE TITLE
Error: Cannot find module '../model/assets/models' when using 4.6.0

### ISSUE THREAD

**Issue by slamuu** [XeroAPI/xero-node#423]
**SDK you're using (please complete the following information):**
 - Version 4.6.0

**Describe the bug**
Missing files in release 4.6.0 when importing libraries and types

```
Error: Cannot find module '../model/assets/models'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (node_modules/xero-node-v4/dist/gen/api/assetApi.js:28:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (node_modules/xero-node-v4/dist/gen/api/apis.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (node_modules/xero-node-v4/dist/index.js:6:10)
```

**To Reproduce**
1. Just import the library from release distribution

**Additional context**
Also notice there are git conflict markers in your distribution code

**Comment by slamuu** [comment]
Whoops discovered the issue was a removal of some file match from `.yarnclean`
