### ISSUE TITLE
ENOENT: no such file or directory, open './package-lock.json'

### ISSUE THREAD

**Issue by adamreisnz** [XeroAPI/xero-node#505]
**SDK you're using (please complete the following information):**
 - Version 4.10.4
 - Node 14.16.0 or 12.21.0

**Describe the bug**
Cannot install package.

**To Reproduce**
1. Add xero-node as dependency with version "^4.10.4"
2. Run npm install or yarn
3. See error

**Expected behavior**
Package installs, with or without a package-lock.json.
Yarn doesn't use package-lock.json for example.

**Screenshots**
```
> xero-node@4.10.4 preinstall node_modules/xero-node
> npx npm-force-resolutions

npx: installed 6 in 2.715s
Error: ENOENT: no such file or directory, open './package-lock.json'
    at Object.openSync (fs.js:476:3)
    at Object.fs [as readFileSync] (fs.js:377:35)
    at npm_force_resolutions$core$node_slurp (.npm/_npx/30752/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:15:20)
    at npm_force_resolutions$core$read_json (.npm/_npx/30752/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:22:23)
    at switch__2144__auto__ (.npm/_npx/30752/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3)
    at .npm/_npx/30752/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3
    at npm_force_resolutions$core$update_package_lock_$_state_machine__2145__auto____1 (.npm/_npx/30752/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:648:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (.npm/_npx/30752/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:664:88)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (.npm/_npx/30752/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (.npm/_npx/30752/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xero-node@4.10.4 preinstall: `npx npm-force-resolutions`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xero-node@4.10.4 preinstall script.
```

Worked fine with 4.10.2

**Comment by Vishanth** [comment]
Having the same issue

**Comment by bkniffler** [comment]
Yes, I've been suffering the same issue when I wanted to deploy. This is a major PITA because it breaks deployments for everyone consuming Xero-node without having a pinned version in package.json.

The cause is one of the latest commits, which added this script:
```
    "preinstall": "npx npm-force-resolutions",
```

I've created a PR.

**Comment by adamreisnz** [comment]
Yep, it's a shame this was released as a patch version, while it clearly
introduces a breaking change.

**Comment by RettBehrens** [comment]
Hi all. I apologize for the inconvenience the previous version released caused. I followed this [guide](https://hackernoon.com/how-fix-security-vulnerabilities-in-npm-dependencies-in-3-minutes-rq9g3y7u) for resolving security vulnerabilities. I have implemented the proposed solution of using prepare instead of preinstall. Please let me know if this continues to be an issue.

**Comment by adamreisnz** [comment]
Yes, I can confirm it is working again in 4.11.0, thank you
