### ISSUE TITLE
Unable to refresh access token after expiry.

### ISSUE THREAD

**Issue by aimensasi** [XeroAPI/xero-node#564]
**SDK you're using (please complete the following information):**
 - Version 4.17.0

**Describe the bug**

unable to refresh access token, receiving below error

```
TypeError: Cannot read property 'refresh' of undefined
    at XeroClient.<anonymous> (/workspace/node_modules/xero-node/dist/XeroClient.js:131:63)
    at Generator.next (<anonymous>)
    at /workspace/node_modules/xero-node/dist/XeroClient.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/node_modules/xero-node/dist/XeroClient.js:23:12)
    at XeroClient.refreshToken (/workspace/node_modules/xero-node/dist/XeroClient.js:127:16)
    at exports.sendTopUpInvoice (/workspace/lib/Concerns/InvoiceConcern.js:44:44)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**To Reproduce**

Token set

```
access_token: ""
expires_at: ":
id_token: ""
refresh_token: ""
scope: "openid profile email accounting.transactions accounting.contacts offline_access"
session_state: ""
token_type: ""
```

The code

```
xero.setTokenSet(credentials.data() as TokenSet);

const tokenSet = xero.readTokenSet();

if (!tokenSet || tokenSet.expired()) {
    const newTokenSet = await xero.refreshToken();
}
```

Note that I have already initialized the SDK and also other calls are working. I am able to create invoices and/or contacts. The only issue is with the refresh

**Comment by aimensasi** [comment]
No update on this, 16 days and no reply. We need to release a feature related to this by 1 Jan. Please let me know if there is anything I need to do.

**Comment by RettBehrens** [comment]
Apologies for the delayed response. 

Hmm, tough to to say without seeing more of the code but from your description it sounds like maybe there's an initialized XeroClient you're using to make your other calls but perhaps defining but not initializing a XeroClient you're attempting to use for refreshing tokens? The error you're getting, `TypeError: Cannot read property 'refresh' of undefined`, leads me to believe the XeroClient was defined since you're able to call `refreshToken` but that it wasn't initialized because that's when `this.openIdClient` is defined.

```public async initialize(): Promise<XeroClient> {
    if (this.config) {
      custom.setHttpOptionsDefaults({
        retry: {
          maxRetryAfter: this.config.httpTimeout || 2500
        }
      })

      const issuer = await Issuer.discover('https://identity.xero.com');
      this.openIdClient = new issuer.Client({
        client_id: this.config.clientId,
        client_secret: this.config.clientSecret,
        redirect_uris: this.config.redirectUris,
      });

      this.openIdClient[custom.clock_tolerance] = 5;
    }
    return this;
  }
```

```public async refreshToken(): Promise<TokenSet> {
    if (!this._tokenSet) {
      throw new Error('tokenSet is not defined');
    }
    const refreshedTokenSet = await this.openIdClient.refresh(this._tokenSet.refresh_token);
    this._tokenSet = new TokenSet(refreshedTokenSet);
    this.setAccessToken();
    return this._tokenSet;
  }
```

**Comment by aimensasi** [comment]
@RettBehrens I tried to reproduce the issue in an isolated environment and the issue persists. 

Here is the full code for the refresh, 

```
    const xero = new XeroClient(config);
    
    await xero.setTokenSet(tokenSet.data()!);
    const tokenData = await xero.readTokenSet();

    try {
      await xero.refreshToken()
    } catch (e) {
      console.log(e);
    }
```

It seems that the client is not initialized and I had to call `xero.initialize()` for it to work.

```
   const xero = new XeroClient(config);

    await xero.setTokenSet(tokenSet.data()!);
    const tokenData = await xero.readTokenSet();
    await xero.initialize(); <--- here

    try {
      await xero.refreshToken()
    } catch (e) {
      console.log(e);
    }
```


Is there a reason for that, or am I doing something wrong here.
