### ISSUE TITLE
Unexpected token o in JSON at position 0

### ISSUE THREAD

**Issue by bevbomb** [XeroAPI/xero-node#69]
I'm receiving the following error after trying to use the client to get all items. Here is the following error stack trace.

``` Text
SyntaxError: Unexpected token o in JSON at position 0
    at Object.parse (native)
    at self.oa.get.stream (/user_code/node_modules/xero-node/lib/application.js:303:33)
    at passBackControl (/user_code/node_modules/xero-node/lib/oauth/oauth.js:406:25)
    at IncomingMessage.<anonymous> (/user_code/node_modules/xero-node/lib/oauth/oauth.js:422:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

https://github.com/XeroAPI/xero-node/blob/910dd1a4b68205cae92740640fcdcd204b1537ba/lib/application.js#L304

**Comment by jordanwalsh23** [comment]
Yes, this is because the data coming back for oauth errors is not valid JSON.  

This is going to be because your oauth token is either invalid, expired, or the signature validation has failed.

To debug I suggest you sign up for a runscope account and place the runscope bucket ID in your config.json.  This will allow you to log the requests and see the exact content so you can resolve your issue.  

In the mean time I'll figure out a way to convert the non-json to json for responding.

**Comment by bevbomb** [comment]
Thank you, I was able to find and fix my issue. 
I figured that the returned results would have been an error of some description.
